#!/bin/sh

mkdir -p build
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DWITH_TRACER_SUPPORT=ON -DWITH_MESSAGE_SET_THREAD_NAME=ON -DWITH_MESSAGE_SET_THREAD_PRIORITY=ON -DWITH_MESSAGE_SET_THREAD_AFFINITY=ON -DWITH_TRACY=OFF -DWITH_TESTS=ON -DWITH_EXAMPLES=ON -DWITH_BOOST_COROUTINES=ON -DWITH_SPDLOG=OFF

